---
jenkins_ver: 2.190.1
jenkins_pkg_url: https://pkg.jenkins.io/debian-stable/binary
jenkins_plugins: 
  - cloudbees-folder
  - antisamy-markup-formatter
  - build-timeout
  - credentials-binding
  - timestamper
  - ws-cleanup
  - ant
  - gradle
  - workflow-aggregator
  - github-branch-source
  - pipeline-github-lib
  - pipeline-stage-view
  - git
  - subversion
  - ssh-slaves
  - matrix-auth
  - pam-auth
  - ldap
  - email-ext
  - mailer
  - blueocean

# vars file for jenkins