version: '3.3'
services:
        web:
            image : nginx
            ports:
               - "8080:80"
            volumes:
            - /srv/docker/nginx/sites-enabled:/etc/nginx/sites-enabled
              restart : always
        db:
            image: mysql
            restart : always
            environment:
                      MYSQL_DATABASE: 'db'
                      MYSQL_USER: 'user'
                      MYSQL_PASSWORD: 'password'
                      MYSQL_ROOT_PASSWORD: 'password'
            ports:
                      - '3306:3306'
            expose:
                      - '3306'
            volumes:
                      - my-db:/var/lib/mysql