---
  - hosts: myServers
    name: Setting Up Docker
    become: yes
    tasks:
      - name: System Update
        apt: 
          update_cache: yes
      - name: Install Packages
        apt: 
          name: "{{ item }}"
          state: latest
          force_apt_get: yes
          update_cache: yes
        with_items:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python-pip
      - name: Add Docker’s official GPG key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
      - name: Add Docker repo
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present
      - name: Install Docker
        apt: 
          update_cache: yes
          name: "{{ item }}"
          state: latest
        with_items:
          - docker-ce
          - docker
          - docker-compose
          - containerd.io
          - docker-ce-cli
      - name: Enable Docker-CE at startup
        service: 
          name: docker
          state: started
          enabled: yes
      - name: Copy docker-compose file
        copy: 
          src: /home/nihit/DevOps/ansible/Docker/wp_mysql.yml
          dest: /home/ubuntu/docker-compose.yml
          mode: '644'
      - name: Install docker-compose using pip
        pip:
          name: docker-compose
        become: true
      - name: Docker-Compose Up
        docker_compose:
          project_src: /home/ubuntu/
          state: present
        register: output